### ISSUE TITLE
"Install pip pt 2" fails to install python 2.7 on Debian 8

### ISSUE THREAD

**Issue by thefinn93** [Stouts/Stouts.python#2]
```
TASK: [Stouts.python | Install pip - pt. 2] *********************************** 
failed: [104.131.152.142] => (item=2.7) => {"changed": false, "cmd": "/usr/bin/python2.7 /usr/share/python/get-pip.py", "delta": "0:00:01.434426", "end": "2015-10-06 15:31:32.979562", "item": 2.7, "rc": 1, "start": "2015-10-06 15:31:31.545136", "stdout_lines": [], "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/share/python/get-pip.py", line 17474, in <module>
    main()
  File "/usr/share/python/get-pip.py", line 17466, in main
    bootstrap(tmpdir=tmpdir)
  File "/usr/share/python/get-pip.py", line 17406, in bootstrap
    import pip
  File "/tmp/tmpGTgc1g/pip.zip/pip/__init__.py", line 11, in <module>
  File "/tmp/tmpGTgc1g/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpGTgc1g/pip.zip/pip/download.py", line 22, in <module>
  File "/tmp/tmpGTgc1g/pip.zip/pip/_vendor/requests/__init__.py", line 53, in <module>
  File "/tmp/tmpGTgc1g/pip.zip/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
ok: [104.131.152.142] => (item=3.4)
```

This is on a fresh Digital Ocean VPS running Debian 8.2

**Comment by thefinn93** [comment]
This appears to be fixable by upgrading `requests` to the latest version. I ran

```
pip install requests
```

on the server and it the role worked after that.

**Comment by thefinn93** [comment]
I fixed this by downloading and running the latest version of [get-pip.py](https://bootstrap.pypa.io/get-pip.py)

**Comment by klen** [comment]
Fixed, thank you for the feedback.
